language: emacs-lisp
sudo: required
dist: trusty
cache:
  - directories:
      - "$HOME/emacs/"
matrix:
  fast_finish: true
env:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
before_install:
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
install:
  - cask install
  - sudo pip install python-language-server
script:
  - cask build
  - cask exec ert-runner -t "!no-win"
  - cask exec ecukes

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3c80316cc2101deff8ce
    on_success: change
    on_failure: always
    on_start: never
