site_name: LSP Mode
site_url: https://emacs-lsp.github.io/lsp-mode

nav:
  - Home: README.md
  - Installation: page/installation.md
  - Keybindings: page/keybindings.md
  - FAQ: page/faq.md
  - Adding new language: page/adding-new-language.md
  - Languages:
    - page/languages.md
    - Ada: page/lsp-ada.md
    - Apple Sourcekit: https://emacs-lsp.github.io/lsp-sourcekit
    - Angular: page/lsp-angular.md
    - Bash: page/lsp-bash.md
    - C++(ccls): page/lsp-ccls.md
    - C++(clangd): page/lsp-clangd.md
    - C++(cquery): page/lsp-cquery.md
    - C#: page/lsp-csharp.md
    - Clojure: page/lsp-clojure.md
    - CMake: page/lsp-cmake.md
    - Crystal: page/lsp-crystal.md
    - CSS/LessCSS/SASS/SCSS: page/lsp-css.md
    - Dart: https://emacs-lsp.github.io/lsp-dart
    - Dhall: page/lsp-dhall.md
    - Dockerfile: page/lsp-dockerfile.md
    - Elixir(elixir-ls): page/lsp-elixir.md
    - Elixir(JakeBecker): page/lsp-elixir-ls.md
    - Elm: page/lsp-elm.md
    - Erlang: page/lsp-erlang.md
    - Eslint: page/lsp-eslint.md
    - F#: page/lsp-fsharp.md
    - Fortran: page/lsp-fortran.md
    - Go(gopls): page/lsp-gopls.md
    - Go(bingo): page/lsp-bingo.md
    - Groovy: page/lsp-groovy.md
    - Hack: page/lsp-hack.md
    - HTML: page/lsp-html.md
    - Haskell: https://emacs-lsp.github.io/lsp-haskell
    - Lua: page/lsp-emmy-lua.md
    - Java: https://emacs-lsp.github.io/lsp-java
    - JavaScript/TypeScript(sourcegraph): page/lsp-typescript.md
    - JavaScript/TypeScript(theia-ide): page/lsp-typescript-javascript.md
    - JavaScript Flow: page/lsp-flow.md
    - Json: page/lsp-json.md
    - Julia: page/lsp-julia.md
    - Kotlin: page/lsp-kotlin.md
    - MSSQL: https://emacs-lsp.github.io/lsp-mssql
    - Nim: page/lsp-nim.md
    - OCaml(ocaml): page/lsp-ocaml.md
    - OCaml(icaml-lsp): page/lsp-ocalm-lsp-server.md
    - Pascal/Object Pascal: page/lsp-pascal.md
    - Perl: page/lsp-perl.md
    - PHP(intelephense): page/lsp-intelephense.md
    - PHP(felixbecker): page/lsp-php.md
    - Powershell: page/lsp-pwsh.md
    - PureScript: page/lsp-purescript.md
    - Python: page/lsp-pyls.md
    - Python(Microsoft): https://emacs-lsp.github.io/lsp-python-ms
    - R: page/lsp-r.md
    - Ruby: page/lsp-solargraph.md
    - Rust: page/lsp-rust.md
    - Scala: page/lsp-metals.md
    - Terraform: page/lsp-terraform.md
    - TeX, LaTeX, etc (digestif): page/lsp-tex.md
    - TeX, LaTeX, etc (texlab): page/lsp-texlab.md
    - TeX, LaTeX, etc (latex): page/lsp-latex.md
    - Verilog/SystemVerilog: page/lsp-verilog.md
    - VHDL: page/lsp-vhdl.md
    - Vimscript: page/lsp-vim.md
    - Vue: page/lsp-vetur.md
    - XML: page/lsp-xml.md
    - YAML: page/lsp-yaml.md
  - Features:
    - page/features.md
    - Debugging: https://emacs-lsp.github.io/dap-mode
    - UI: https://emacs-lsp.github.io/lsp-ui
    - Treemacs: https://github.com/emacs-lsp/lsp-treemacs
    - Helm: https://github.com/emacs-lsp/helm-lsp
    - Ivy: https://github.com/emacs-lsp/lsp-ivy
  - Gallery:
      - page/gallery.md
  - Changelog:
      - page/CHANGELOG.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/expanded_nav.js

theme:
  name: material
  logo: examples/logo-mini.png
  favicon: examples/logo-mini.png
  icon:
    repo: fontawesome/brands/github
  features:
    - tabs

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/emacs-lsp/lsp-mode
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yonchovski
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/emacs-lsp/lsp-mode

repo_name: emacs-lsp/lsp-mode
repo_url: https://github.com/emacs-lsp/lsp-mode

markdown_extensions:
  - pymdownx.superfences
  - codehilite
  - toc:
      permalink: '#'

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized
