site_name: LSP Mode - LSP support for Emacs
site_url: https://emacs-lsp.github.io/lsp-mode

nav:
  - Home:
    - Overview: README.md
    - Setup:
        - Installation: page/installation.md
        - Performance: page/performance.md
    - Main features: page/main-features.md
    - Settings: page/settings.md
    - Keybindings: page/keybindings.md
    - Extensions:
        - UI: https://emacs-lsp.github.io/lsp-ui
        - Treemacs: https://github.com/emacs-lsp/lsp-treemacs
        - Helm: https://github.com/emacs-lsp/helm-lsp
        - Ivy: https://github.com/emacs-lsp/lsp-ivy
    - Limitations: page/limitations.md
    - Remote: page/remote.md
    - FAQ: page/faq.md
    - Troubleshooting: page/troubleshooting.md
    - Adding new language: page/adding-new-language.md
  - Languages:
    - page/languages.md
    - Ada: page/lsp-ada.md
    - Angular: page/lsp-angular.md
    - Bash: page/lsp-bash.md
    - C++ (ccls): page/lsp-ccls.md
    - C++ (clangd): page/lsp-clangd.md
    - C#: page/lsp-csharp.md
    - Clojure: page/lsp-clojure.md
    - CMake: page/lsp-cmake.md
    - Crystal: page/lsp-crystal.md
    - CSS/LessCSS/SASS/SCSS: page/lsp-css.md
    - Dart: https://emacs-lsp.github.io/lsp-dart
    - Dhall: page/lsp-dhall.md
    - Dockerfile: page/lsp-dockerfile.md
    - Elixir: page/lsp-elixir.md
    - Elm: page/lsp-elm.md
    - Erlang: page/lsp-erlang.md
    - Eslint: page/lsp-eslint.md
    - F#: page/lsp-fsharp.md
    - Fortran: page/lsp-fortran.md
    - GDScript: page/lsp-gdscript.md
    - Go (gopls): page/lsp-gopls.md
    - Go (bingo): page/lsp-bingo.md
    - Groovy: page/lsp-groovy.md
    - Hack: page/lsp-hack.md
    - HTML: page/lsp-html.md
    - Haskell: https://emacs-lsp.github.io/lsp-haskell
    - Lua (EmmyLua): page/lsp-emmy-lua.md
    - Lua (Lua Language Server): page/lsp-lua-language-server.md
    - Lua (Lua-Lsp): page/lsp-lua-lsp.md
    - Java: https://emacs-lsp.github.io/lsp-java
    - JavaScript/TypeScript (sourcegraph): page/lsp-typescript-javascript.md
    - JavaScript/TypeScript (theia-ide): page/lsp-typescript.md
    - JavaScript Flow: page/lsp-flow.md
    - Json: page/lsp-json.md
    - Julia: page/lsp-julia.md
    - Kotlin: page/lsp-kotlin.md
    - MSSQL: https://emacs-lsp.github.io/lsp-mssql
    - Nim: page/lsp-nim.md
    - Nix: page/lsp-nix.md
    - OCaml (ocaml): page/lsp-ocaml.md
    - OCaml (icaml-lsp): page/lsp-ocalm-lsp-server.md
    - Pascal/Object Pascal: page/lsp-pascal.md
    - Perl: page/lsp-perl.md
    - PHP (intelephense): page/lsp-intelephense.md
    - PHP (Serenata): page/lsp-serenata.md
    - PHP (felixbecker): page/lsp-php.md
    - Powershell: page/lsp-pwsh.md
    - PureScript: page/lsp-purescript.md
    - Python: page/lsp-pyls.md
    - Python (Pyright): https://emacs-lsp.github.io/lsp-pyright
    - Python (Microsoft): https://emacs-lsp.github.io/lsp-python-ms
    - R: page/lsp-r.md
    - Ruby: page/lsp-solargraph.md
    - Rust: page/lsp-rust.md
    - Scala: https://emacs-lsp.github.io/lsp-metals
    - SQL (sqls): page/lsp-sqls.md
    - Svelte: page/lsp-svelte.md
    - Swift: https://emacs-lsp.github.io/lsp-sourcekit
    - Terraform: page/lsp-terraform.md
    - TeX, LaTeX, etc (digestif): page/lsp-tex.md
    - TeX, LaTeX, etc (texlab): page/lsp-texlab.md
    - TeX, LaTeX, etc (texlab, external): page/lsp-latex.md
    - Verilog/SystemVerilog: page/lsp-verilog.md
    - VHDL: page/lsp-vhdl.md
    - Vimscript: page/lsp-vim.md
    - Vue: page/lsp-vetur.md
    - XML: page/lsp-xml.md
    - YAML: page/lsp-yaml.md
  - Debugging:
      - https://emacs-lsp.github.io/dap-mode
  - Gallery:
      - page/gallery.md
  - Changelog:
      - page/CHANGELOG.md
  - Blog:
      - 2020:
          - '7.0 Release': blog/2020/7.0-release.md
  - Support us:
      - https://opencollective.com/emacs-lsp

extra_css:
  - stylesheets/layout.css
  - stylesheets/members.css

extra_javascript:
  - js/expanded_nav.js

theme:
  name: material
  logo: examples/logo-mini.png
  favicon: examples/logo-mini.png
  icon:
    repo: fontawesome/brands/github
  features:
    - tabs

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/emacs-lsp/lsp-mode
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yonchovski
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/emacs-lsp/lsp-mode

repo_name: emacs-lsp/lsp-mode
repo_url: https://github.com/emacs-lsp/lsp-mode

markdown_extensions:
  - pymdownx.superfences
  - codehilite
  - meta
  - toc:
      permalink: '#'
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized

google_analytics:
  - UA-165661257-1
  - auto
