site_name: LSP Mode - LSP support for Emacs
site_description: Language Server Protocol Support for Emacs
site_url: https://emacs-lsp.github.io/lsp-mode
site_author: ercdll1337@gmail.com
base_url: https://github.com/emacs-lsp/lsp-mode

nav:
  - Home:
    - Overview: README.md
    - Setup:
        - Installation: page/installation.md
        - Performance: page/performance.md
    - Main features: page/main-features.md
    - Keybindings: page/keybindings.md
    - Extensions:
        - UI: https://emacs-lsp.github.io/lsp-ui
        - Treemacs: https://github.com/emacs-lsp/lsp-treemacs
        - Helm: https://github.com/emacs-lsp/helm-lsp
        - Ivy: https://github.com/emacs-lsp/lsp-ivy
        - Iedit: page/integration/iedit.md
        - Ido: page/integration/ido.md
    - File watchers: page/file-watchers.md
    - Remote: page/remote.md
    - FAQ: page/faq.md
    - Troubleshooting: page/troubleshooting.md
    - Adding new language: page/adding-new-language.md
  - Settings:
    - Features:
      - Core: page/settings/mode.md
      - Completion: page/settings/completion.md
      - Diagnostics: page/settings/diagnostics.md
      - Headerline: page/settings/headerline.md
      - Modeline: page/settings/modeline.md
      - Lens: page/settings/lens.md
      - Icons: page/settings/icons.md
      - Semantic Tokens: page/settings/semantic-tokens.md
    - Extensions:
      - UI: https://emacs-lsp.github.io/lsp-ui
      - Treemacs: https://github.com/emacs-lsp/lsp-treemacs
      - Helm: https://github.com/emacs-lsp/helm-lsp
      - Ivy: https://github.com/emacs-lsp/lsp-ivy
      - Consult: https://github.com/gagbo/consult-lsp
      - Dired: page/settings/dired.md
      - Iedit: page/settings/iedit.md
      - Ido: page/settings/ido.md
  - Languages:
    - page/languages.md
    - ActionScript: page/lsp-actionscript.md
    - Ada: page/lsp-ada.md
    - Angular: page/lsp-angular.md
    - Ansible: page/lsp-ansible.md
    - Assembly: page/lsp-asm.md
    - Astro: page/lsp-astro.md
    - Autotools: page/lsp-autotools.md
    - AWK: page/lsp-awk.md
    - Bash: page/lsp-bash.md
    - Beancount: page/lsp-beancount.md
    - Camel: page/lsp-camel.md
    - C++ (ccls): page/lsp-ccls.md
    - C++ (clangd): page/lsp-clangd.md
    - C# (omnisharp-roslyn): page/lsp-csharp-omnisharp.md
    - C# (csharp-roslyn): page/lsp-csharp-roslyn.md
    - C# (csharp-ls): page/lsp-csharp-ls.md
    - Clojure: page/lsp-clojure.md
    - CMake: page/lsp-cmake.md
    - COBOL: page/lsp-cobol.md
    - Crystal: page/lsp-crystal.md
    - CSS/LessCSS/SASS/SCSS: page/lsp-css.md
    - Cucumber: page/lsp-cucumber.md
    - Cypher: page/lsp-cypher.md
    - D: page/lsp-d.md
    - Dart: https://emacs-lsp.github.io/lsp-dart
    - Dhall: page/lsp-dhall.md
    - Dockerfile: page/lsp-dockerfile.md
    - Earthfile: page/lsp-earthly.md
    - Elixir: page/lsp-elixir.md
    - Elm: page/lsp-elm.md
    - Emmet: page/lsp-emmet.md
    - Erlang: page/lsp-erlang.md
    - ESLint: page/lsp-eslint.md
    - F#: page/lsp-fsharp.md
    - Fortran: page/lsp-fortran.md
    - GDScript: page/lsp-gdscript.md
    - Gleam: page/lsp-gleam.md
    - GLSL: page/lsp-glsl.md
    - GNAT Project: page/lsp-gpr.md
    - Go (gopls): manual-language-docs/lsp-gopls.md
    - Grammarly: page/lsp-grammarly.md
    - GraphQL: page/lsp-graphql.md
    - Groovy: page/lsp-groovy.md
    - Hack: page/lsp-hack.md
    - HTML: page/lsp-html.md
    - Haskell: https://emacs-lsp.github.io/lsp-haskell
    - Hy (hyuga): page/lsp-hy.md
    - Idris: page/lsp-idris.md
    - Java: https://emacs-lsp.github.io/lsp-java
    - Javascript/Typescript (deno): page/lsp-deno.md
    - JavaScript/TypeScript (sourcegraph): page/lsp-typescript-javascript.md
    - JavaScript/TypeScript (theia-ide): page/lsp-typescript.md
    - JavaScript Flow: page/lsp-flow.md
    - Json: page/lsp-json.md
    - Jsonnet: page/lsp-jsonnet.md
    - Julia: page/lsp-julia.md
    - Kotlin: page/lsp-kotlin.md
    - LanguageTool (LTEX): page/lsp-ltex.md
    - Lisp: page/lsp-lisp.md
    - Lua (EmmyLua): page/lsp-emmy-lua.md
    - Lua (Lua Language Server): page/lsp-lua-language-server.md
    - Lua (Lua-Lsp): page/lsp-lua-lsp.md
    - Magik: page/lsp-magik.md
    - Markdown: page/lsp-markdown.md
    - Marksman: page/lsp-marksman.md
    - Meson: page/lsp-meson.md
    - Move: page/lsp-move.md
    - MDX: page/lsp-mdx.md
    - MSSQL: https://emacs-lsp.github.io/lsp-mssql
    - Nginx: page/lsp-nginx.md
    - Nim: page/lsp-nim.md
    - Nix (nixd-lsp): page/lsp-nix-nixd.md
    - Nix (rnix-lsp): page/lsp-nix-rnix.md
    - Nix (nil): page/lsp-nix-nil.md
    - Nushell: page/lsp-nushell.md
    - OCaml (ocaml-lsp): page/lsp-ocaml-lsp-server.md
    - OpenSCAD: page/lsp-openscad.md
    - Pascal/Object Pascal: page/lsp-pascal.md
    - Perl (PLS): page/lsp-pls.md
    - Perl (Perl::LanguageServer): page/lsp-perl.md
    - Perl (Navigator): page/lsp-perlnavigator.md
    - PHP (intelephense): page/lsp-intelephense.md
    - PHP (Serenata): page/lsp-serenata.md
    - PHP (felixbecker): page/lsp-php.md
    - PHP (phpactor): page/lsp-phpactor.md
    - Powershell: page/lsp-pwsh.md
    - Prolog: page/lsp-prolog.md
    - PureScript: page/lsp-purescript.md
    - Python (Pylsp): page/lsp-pylsp.md
    - Python (Jedi Language Server): page/lsp-jedi.md
    - Python (Palantir deprecated): page/lsp-pyls.md
    - Python (Pyright): https://emacs-lsp.github.io/lsp-pyright
    - Python (Microsoft): https://emacs-lsp.github.io/lsp-python-ms
    - Python (Ruff): page/lsp-ruff.md
    - QML: page/lsp-qml.md
    - R: page/lsp-r.md
    - Racket (jeapostrophe): page/lsp-racket-langserver.md
    - Racket (Theia): page/lsp-racket-language-server.md
    - RPM Spec: page/lsp-rpm-spec.md
    - Ruby (RuboCop): page/lsp-rubocop.md
    - Ruby (ruby-lsp): page/lsp-ruby-lsp.md
    - Ruby (Solargraph): page/lsp-solargraph.md
    - Ruby (Sorbet): page/lsp-sorbet.md
    - Ruby (Steep): page/lsp-steep.md
    - Ruby (TypeProf): page/lsp-typeprof.md
    - Rust (rust-analyzer): page/lsp-rust-analyzer.md
    - Rust (rls): page/lsp-rust-rls.md
    - Scala: https://emacs-lsp.github.io/lsp-metals
    - Semgrep: page/lsp-semgrep.md
    - ShaderLab: page/lsp-shader.md
    - SQL (sql): page/lsp-sql.md
    - SQL (sqls): page/lsp-sqls.md
    - Standard ML (Millet): page/lsp-sml.md
    - Svelte: page/lsp-svelte.md
    - Swift: https://emacs-lsp.github.io/lsp-sourcekit
    - Terraform (terraform-lsp): page/lsp-terraform.md
    - Terraform (terraform-ls): page/lsp-terraform-ls.md
    - TeX, LaTeX, etc (digestif): page/lsp-tex.md
    - TeX, LaTeX, etc (texlab): page/lsp-texlab.md
    - TeX, LaTeX, etc (texlab, external): page/lsp-latex.md
    - Tilt: page/lsp-tilt.md
    - TOML: page/lsp-toml.md
    - Trunk: page/lsp-trunk.md
    - TTCN3: page/lsp-ttcn3.md
    - V: page/lsp-v.md
    - Vala: page/lsp-vala.md
    - Verilog/SystemVerilog (hdl-checker): page/lsp-verilog.md
    - Verilog/SystemVerilog (svlangserver): page/lsp-svlangserver.md
    - Verilog/SystemVerilog (verible): page/lsp-verible.md
    - VHDL: page/lsp-vhdl.md
    - Vimscript: page/lsp-vimscript.md
    - Vue 2: page/lsp-vetur.md
    - Vue 3: page/lsp-volar.md
    - wgsl: page/lsp-wgsl.md
    - XML: page/lsp-xml.md
    - YAML: page/lsp-yaml.md
    - YANG: page/lsp-yang.md
    - Zig: page/lsp-zig.md
  - Debugging:
      - https://emacs-lsp.github.io/dap-mode
  - Gallery:
      - page/gallery.md
  - Changelog:
      - page/CHANGELOG.md
  - Tutorials:
      - 'Configuring Emacs as a C/C++ IDE': tutorials/CPP-guide.md
      - 'Configuring Emacs as a PHP IDE': tutorials/php-guide.md
      - 'A guide on disabling/enabling lsp-mode features': tutorials/how-to-turn-off.md
      - 'React JavaScript Tutorial in Emacs': tutorials/reactjs-tutorial.md
      - 'Configuring Emacs as a Clojure IDE': tutorials/clojure-guide.md
      - 'Debugging Clojurescript': tutorials/debugging-clojure-script.md
      - 'Python, debbuging with poetry + pyenv': https://emacs-lsp.github.io/dap-mode/page/python-poetry-pyenv/
      - 'Configuring Emacs as a Crystal IDE': tutorials/crystal-guide.md
  - Blog:
      - 2020:
          - '7.0 Release': blog/2020/7.0-release.md
  - Support us:
      - https://github.com/sponsors/emacs-lsp

extra_css:
  - stylesheets/layout.css
  - stylesheets/members.css

extra_javascript:
  - js/expanded_nav.js

theme:
  name: material
  custom_dir: overrides
  logo: examples/logo-mini.png
  favicon: examples/logo-mini.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/emacs-lsp/lsp-mode
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yonchovski
    - icon: fontawesome/brands/discord
      link: https://discord.gg/swuxy5AAgT

repo_name: emacs-lsp/lsp-mode
repo_url: https://github.com/emacs-lsp/lsp-mode

markdown_extensions:
  - pymdownx.superfences
  - codehilite
  - meta
  - toc:
      permalink: '#'
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized
  - rss

google_analytics:
  - UA-165661257-1
  - auto
