name: Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CHANGELOG.org -> CHANGELOG.md
        uses: docker://pandoc/core:2.9
        with:
          args: -s CHANGELOG.org -t gfm -o docs/page/CHANGELOG.md

      - uses: purcell/setup-emacs@master
        with:
          version: 27.1

      - uses: conao3/setup-cask@master
        with:
          version: 0.8.4

      - name: Generate LSPs docs
        run: 'make docs'

      - name: MkDocs
        run: |
          cp -rf README.md examples docs

          docker login docker.pkg.github.com --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
          docker run --rm -v ${PWD}:/docs docker.pkg.github.com/emacs-lsp/docs-image/docs-image -- build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
