name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version:
          - 26.3
          - 27.2
          - 28.2
          - 29.1
        experimental: [false]
        include:
          - os: ubuntu-latest
            emacs-version: snapshot
            experimental: true
          - os: macos-latest
            emacs-version: snapshot
            experimental: true
          - os: windows-latest
            emacs-version: snapshot
            experimental: true

    steps:
    - uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - name: Setup cmake
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      uses: jwlawson/actions-setup-cmake@v1.4
      with:
        cmake-version: '3.18.x'

    - name: Check cmake
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: "cmake --version"
      
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"
        architecture: "x64"
      
    - name: Install depedencies on Linux
      if: runner.os == 'Linux'
      run: |
        pip3 install python-language-server
        sudo apt-get install clangd-11

    - name: Install depedencies on macOS
      if: runner.os == 'macOS'
      run: |
        pip3 install python-language-server

    - name: Check clangd
      if: runner.os == 'Linux'
      run: "clangd-11 --version"

    - uses: actions/checkout@v3

    - name: Grant execution permission
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: chmod -R 777 ./

    - name: Run tests (Unix)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: make unix-ci

    - name: Run tests (Windows)
      if: matrix.os == 'windows-latest'
      run: make windows-ci

    - name: Move built artifact (Unix)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: |
        mv -f ./.eask/ ./test/downstream/.eask/
        mv -f ./dist/ ./test/downstream/dist/

    - name: Move built artifact (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        mv -Force ./.eask/ ./test/downstream/.eask/
        mv -Force ./dist/ ./test/downstream/dist/

    - name: Test downstream packages
      run: make test-downstream-pkgs
